### ISSUE TITLE
[MXNET] Activation in yaml and calibration algorithm

### ISSUE THREAD

**Issue by PawelGlomski-Intel** [intel/lpot#10]
Hi, I would like to contribute and improve MXNet integration and add MXNet 1.9 support, but one thing is not clear to me.

I would like to ask what exactly does the "activation" of an operator mean in "capabilities", especially its "algorithm" attribute. I thought this meant the operator's input (as stated [here](https://github.com/intel/lpot/blob/master/docs/adaptor.md#query-api)), and the "algorithm" attribute determines whether minmax or kl will be used when calibrating that operator's input tensors, but I believe this is not what is happening in MXNet adaptor.
https://github.com/intel/lpot/blob/v1.3.1/lpot/adaptor/mxnet.py#L581-L592
Here, `calib_minmax_layers ` and `calib_kl_layers`  are filled with the names of the operators' outputs, not their inputs. Is this intentional?

Thanks

**Comment by ftian1** [comment]
Pawel, thanks for your contribution.

as for how to explain the acivation field of query API, we treat it as input and output datatype at the same time. so fp32 means fallback to FP32. u8 means u8 in u8 out. s8 means s8 in s8 out.
