### ISSUE TITLE
AttributeError: 'list' object has no attribute 'shape'

### ISSUE THREAD

**Issue by peiwenhuang27** [intel/lpot#15]
LPOT Version: 1.4
Installation: source
Environment: Google Colab
Framework: ONNX (as specified in requirements.txt in the [example](https://github.com/intel/lpot/tree/master/examples/onnxrt/object_detection/ssd_mobilenet_v1))

I used a common dataloader to load my own dataset in `main.py` (using numpy array to store the data) as below:

        tuneDataset = Dataset('tune')
        evalDataset = Dataset('eval')
        
        quantize = Quantization(args.config)
        quantize.model = common.Model(model)
        quantize.calib_dataloader = common.DataLoader(tuneDataset, batch_size=64, last_batch='drop')
        quantize.eval_dataloader = common.DataLoader(evalDataset, batch_size=64, last_batch='drop')
        q_model = quantize()
        q_model.save(args.output_model)

In the line `q_model = quantize()`, it was getting FP32 model baseline, and then the error occurs:

==========================================
Traceback (most recent call last):
  File "main.py", line 112, in <module>
    q_model = quantize()
  File "/usr/local/lib/python3.7/dist-packages/lpot-1.4.1-py3.7.egg/lpot/experimental/quantization.py", line 176, in __call__
    self.strategy.traverse()
  File "/usr/local/lib/python3.7/dist-packages/lpot-1.4.1-py3.7.egg/lpot/strategy/strategy.py", line 286, in traverse
    self.baseline = self._evaluate(self.model)
  File "/usr/local/lib/python3.7/dist-packages/lpot-1.4.1-py3.7.egg/lpot/strategy/strategy.py", line 424, in _evaluate
    val = self.objective.evaluate(eval_func, model)
  File "/usr/local/lib/python3.7/dist-packages/lpot-1.4.1-py3.7.egg/lpot/objective.py", line 213, in evaluate
    acc = eval_func(model)
  File "/usr/local/lib/python3.7/dist-packages/lpot-1.4.1-py3.7.egg/lpot/utils/create_obj_from_config.py", line 131, in eval_func
    tensorboard, fp32_baseline)
  File "/usr/local/lib/python3.7/dist-packages/lpot-1.4.1-py3.7.egg/lpot/adaptor/onnxrt.py", line 419, in evaluate
    metric.update(predictions, labels)
  File "/usr/local/lib/python3.7/dist-packages/lpot-1.4.1-py3.7.egg/lpot/experimental/metric/metric.py", line 491, in update
    preds, labels = _shape_validate(preds, labels)
  File "/usr/local/lib/python3.7/dist-packages/lpot-1.4.1-py3.7.egg/lpot/experimental/metric/metric.py", line 268, in _shape_validate
    of labels {} does not match shape of predictions {}'.format(labels.shape, preds.shape)
AttributeError: 'list' object has no attribute 'shape'

**Comment by peiwenhuang27** [comment]
I used the same model to run quantization under Tensorflow (the above ONNX model is converted from my Tensorflow model), and when evaluating FP32 model baseline, this error does not seem to arise as it successfully outputs the metrics. 
So maybe this issue has something to do with the adaptor?

**Comment by ftian1** [comment]
@peiwenhuang27 this error happens only when labels and preds are different type/data shape/length. could you pls print the labels and preds details and share to us?

**Comment by peiwenhuang27** [comment]
I loaded the ONNX model and ran inference using my data, and here's a snippet of the inference code:

```
model = './model.onnx'
session = onnxruntime.InferenceSession(model, None)
input_name = session.get_inputs()[0].name
output_name = session.get_outputs()[0].name
preds = session.run([output_name], {input_name: x[:64]}) # batch_size = 64
```

I printed my result to check, and as it turns out the `preds` object is a **list of np array**, like this: 
`[array([[[...]]])]` where preds[0].shape = (64, 60, 257)

My labels are stored as pure **np array**:

```
labels = y[:64]
print(type(labels)) # numpy.ndarray
print(labels.shape) # (64, 60, 257)
```

So their shapes appear to be the same.
On the other hand, when using LPOT, I used a custom Common dataloader like the following:

```
class Dataset(object):
  def __init__(self, mode):
    self.x = np.empty((0, 257, 60, 1), np.float32)
    self.y = np.empty((0, 60, 257), np.float32)
    if mode == 'tune': # tune
        x_tmp = np.load('./trainingData/x0.npy')
        self.x = np.append(self.x, x_tmp, axis=0)
        y_tmp = np.load('./trainingData/y0.npy')
        self.y = np.append(self.y, y_tmp, axis=0)

    else: # benchmark
      x_tmp = np.load('./trainingData/x1.npy')
      self.x = np.append(self.x, x_tmp, axis=0)
      y_tmp = np.load('./trainingData/y1.npy')
      self.y = np.append(self.y, y_tmp, axis=0)

    self.x = np.array(self.x).astype(np.float32)
    self.y = np.array(self.y).astype(np.float32)

  def __getitem__(self, index):
      return self.x[index], self.y[index]
  def __len__(self):
      return len(self.x)
```

I also used this dataloader class to run quantization under Tensorflow framework, and the results seem fine.

Could the error be caused by the fact that ONNX model outputs a list object instead of np array?

**Comment by ftian1** [comment]
> it turns out the `preds` object is a **list of np array**, like this:
> `[array([[[...]]])]` where preds[0].shape = (64, 60, 257)

Yes, the problem is because preds is a list but labels is just a numpy.array. you can have a try to return list of label in Dataset.__getitem__()

```
  def __getitem__(self, index):
      return self.x[index], [self.y[index]]    # like below
```

**Comment by peiwenhuang27** [comment]
Yes, I am using built-in MSE to evaluate the loss.
And thank you so much for the workaround, the code runs fine now!
