### ISSUE TITLE
Timeout issue when quantizing BERT large squad model

### ISSUE THREAD

**Issue by ppalania21** [intel/lpot#22]
I have been following these steps to quantize BERT model - https://github.com/intel/lpot/tree/master/examples/tensorflow/nlp/bert_large_squad.

While running the below command for quantization:
python tune_squad.py --config=./bert.yaml --input_model=./bert_fp32.pb --output_model=./int8.pb --tune

I see a timeout/crash with the following message:
[ERROR] Specified timeout or max trials is reached! Not found any quantized model which meet accuracy goal.

Error log - [bert_quantization_error.txt](https://github.com/intel/lpot/files/6887763/bert_quantization_error.txt)
yaml config file I am using - [bert.yaml.txt](https://github.com/intel/lpot/files/6887767/bert.yaml.txt)

**Comment by guomingz** [comment]
@ppalania21 will try tf1.15up2 on it and send the update later.

**Comment by ppalania21** [comment]
I was able to confirm that BERT Int8 model works fine on TF1.15up2.
