### ISSUE TITLE
list index out of range in ResNet50 example

### ISSUE THREAD

**Issue by kenkoyanagi** [intel/lpot#4]
**Environment:** 
Windows 10
LPOT master
ResNet50 ONNX model IRv11
ONNX 1.8.1
ORT 1.6.0

Running the example in examples/onnxrt/image_recognition/resnet50: 
`run_tuning.bat resnet50.onnx resnet50_v1_5.yaml test `

yields the error: 
IndexError: list index out of range @ line 143 get_intermediate_outputs in onnx_calibrate.py 
the intermediate_outputs list is empty. 

> Traceback (most recent call last):   File "main.py", line 85, in <module>     q_model = quantize(model)   File "C:\Users\kkoyanag\AppData\Local\Programs\Python\Python36\lib\site-packages\lpot-1.1-py3.6.egg\lpot\quantization.py", line 219, in __call__     self.strategy.traverse()   File "C:\Users\kkoyanag\AppData\Local\Programs\Python\Python36\lib\site-packages\lpot-1.1-py3.6.egg\lpot\strategy\strategy.py", line 284, in traverse     tune_cfg, self.model, self.calib_dataloader, self.q_func)   File "C:\Users\kkoyanag\AppData\Local\Programs\Python\Python36\lib\site-packages\lpot-1.1-py3.6.egg\lpot\adaptor\onnxrt.py", line 82, in quantize     quantize_params = self._get_quantize_params(model, dataLoader, q_config, iterations)   File "C:\Users\kkoyanag\AppData\Local\Programs\Python\Python36\lib\site-packages\lpot-1.1-py3.6.egg\lpot\adaptor\onnxrt.py", line 102, in _get_quantize_params     q_config["nodes_exclude"], q_config["nodes_include"], iterations=iterations)   File "C:\Users\kkoyanag\AppData\Local\Programs\Python\Python36\lib\site-packages\lpot-1.1-py3.6.egg\lpot\adaptor\ox_utils\onnx_calibrate.py", line 295, in calibrate     dict_for_quantization = calibrater.get_intermediate_outputs()   File "C:\Users\kkoyanag\AppData\Local\Programs\Python\Python36\lib\site-packages\lpot-1.1-py3.6.egg\lpot\adaptor\ox_utils\onnx_calibrate.py", line 143, in get_intermediate_outputs     range(len(intermediate_outputs[0]))] IndexError: list index out of range

**Comment by airMeng** [comment]
hi kenkoyanagi:
    thanks for your reporting this issue. 
>ResNet50 ONNX model IRv11

 can you confirm it is opset=11 or ir_version=11, because from ONNX [doc](https://github.com/onnx/onnx/blob/master/docs/Versioning.md#released-versions), the lasted ir_version is 7.
otherwise, we validated RN50 with opset=11&12 , could you please give more details?

**Comment by kenkoyanagi** [comment]
Hi @airMeng, sorry I mixed up the terminology. It's Opset 11.

**Comment by ftian1** [comment]
issue solved by mail discussion. it's dataset related question and need follow dataset doc to fill correct dataset type in yaml.
