### ISSUE TITLE
[keras example] AttributeError: 'NoneType' object has no attribute 'items'

### ISSUE THREAD

**Issue by peiwenhuang27** [intel/lpot#9]
**Environment**: Google Colab, Tensorflow 1.15.0

I was trying out one of the examples (examples/tensorflow/keras), and when I was running benchmark session, I got the following error:

> Traceback (most recent call last):
>   File "main.py", line 76, in <module>
>     evaluate_opt_graph.run()
>   File "main.py", line 63, in run
>     for mode, result in results.items():
> AttributeError: 'NoneType' object has no attribute 'items'

So I opened the file `main.py` to inspect the code:

`results = evaluator()`
`for mode, result in results.items():`

It seems that `results` is a *NoneType* object, which caused the error.

---
On another note, I wanted to ask about how to setup config for the quantization:
1. How do I specify the type of quantization, e.g. **full integer quantization** or **16x8 integer quantization**? I see the current method seems to employ the full integer method. So I opened that the sample config file to try to edit the method, but ended up seeing the following parameters
  ` model_wise:`
        `activation:`
                 `algorithm: minmax`
   I'm not sure how this connects to the quantization method, any hints/help would be greatly appreciated.
2. Just to be sure, the benchmark statistic
   `FP32 baseline is: [0.1135, 138.3854] ` list object refers to accuracy, and loss respectively right?

Thanks in advance. 😃

**Comment by mengniwang95** [comment]
Hi, for the benchmark error, the results are printed automatically after running, line63~71 should be removed and we have fixed it in the next release.
Question 1: the algorithm is the way to calculate the scale of nodes during quantization
Question 2: the baseline lists [accuracy, latency] in order

**Comment by peiwenhuang27** [comment]
Thanks for the answer, it worked fine now. I did encounter another problem though, I will open another issue for that.

**Comment by ftian1** [comment]
@peiwenhuang27  pls use latest LPOT, in which we have improved logging message. you will see something like

FP32 baseline is: [accuracy: 0.1135, duration(second): 138.3854]

rather than 

FP32 baseline is: [0.1135, 138.3854]

**Comment by ftian1** [comment]
as for specifying quantization type, LPOT only supports u8/s8 quantization.
